### ISSUE TITLE
Using upstream version number for the smart package version.

### ISSUE THREAD

**Issue by KerimG** [matteodem/meteor-gridster#1]
Hey mate, thanks for wrapping gridster, but could you please use the upstream version number for the smart package's version number (unless you modified yours)? It makes things a lot easier when searching for packages with "meteor show". 

Discussion from the IRC channel about this: 

<z1mme> kerimg: you should open an issue with the wrapper package and encurage him to use upstream versioning, and if be does wrapper package specific changes and need to publish a new version with the same lib version then he can use the 0.5.6_1 versions
<kerimg> Think I'll do that, thanks.
<z1mme> that's why meteor did that syntax for versioning, to help with "wrapper" packages

Thanks for your effort and best regards!

**Comment by matteodem** [comment]
Hey Kerim

What do you mean with upstream versioning? Any good example?

**Comment by KerimG** [comment]
I creatred a pull request with the necessary change :)
